arch: x86_64
image: fedora/latest
packages:
  - gcc
  - cmake
  - 'arm-none-eabi-*'
  - gcc-c++
  - clang-tools-extra
sources:
  - "https://git.sr.ht/~gary-kim/gkrtos"
tasks:
  - install: |
      cd gkrtos
      mkdir tmp
      cd tmp
      cmake ..
      make -j $(nproc)
  - format: |
      cd gkrtos
      ./scripts/clang-format-check.sh
triggers:
  - action: email
    condition: always
    to: "Gary Kim <gary.kim@cooper.edu>"

