arch: x86_64
image: fedora/latest
packages:
  - gcc
  - cmake
  - 'arm-none-eabi-*'
  - gcc-c++
  - clang-tools-extra
sources:
  - "git@git.sr.ht:~gary-kim/gkrtos"
secrets:
  - 5de7ec36-b900-47ba-be3d-4303475f46c2
tasks:
  - install: |
      cd gkrtos
      mkdir tmp
      cd tmp
      cmake ..
      make -j $(nproc)
  - format: |
      cd gkrtos
      ./scripts/clang-format-check.sh
triggers:
  - action: email
    condition: always
    to: "Gary Kim <gary.kim@cooper.edu>"

